services:
  sudarshana:
    image: sudarshana:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .env:/app/.env
