apiVersion: v1
kind: Service
metadata:
  name: sudarshana-service
  labels:
    app: sudarshana
spec:
  selector:
    app: sudarshana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP