apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sudarshana-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sudarshana.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sudarshana-service
            port:
              number: 80